version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - /c/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"